In [15]:
import pandas

In [16]:
data = pandas.read_csv('/content/titanic.csv')

In [17]:
data.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [10]:
len(data)

891

In [11]:
min(data)

'age'

In [12]:
max(data)

'survived'

In [13]:
data.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

In [14]:
data[ ["survived" , "sex",'age'] ]

     survived     sex   age
0           0    male  22.0
1           1  female  38.0
2           1  female  26.0
3           1  female  35.0
4           0    male  35.0
..        ...     ...   ...
886         0    male  27.0
887         1  female  19.0
888         0  female   NaN
889         1    male  26.0
890         0    male  32.0

[891 rows x 3 columns]